import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234'),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: 'free shirt',
      category: 'Shirts',
      slug: 'shirts',
      image: '/images/shirt1.jpeg',
      banner: '/images/shirt1.jpeg',
      price: 20,
      brand: 'nike',
      description: 'free shirt',
      rating: 4.5,
      numReviews: 6,
      countInStock: 20,
      isFeatured: true,
    },

    {
      name: 'free shirt 2',
      category: 'Shirts',
      slug: 'shirts-2',
      image: '/images/shirt2.jpeg',
      banner: '/images/shirt1.jpeg',
      price: 30,
      brand: 'nike',
      description: 'free shirt 2',
      rating: 4.5,
      numReviews: 6,
      countInStock: 20,
      isFeatured: true,
    },
    {
      name: 'free shirt 3',
      category: 'Shirts',
      slug: 'shirts-3',
      image: '/images/shirt3.jpeg',
      banner: '/images/shirt1.jpeg',
      price: 22,
      brand: 'nike',
      description: 'free shirt 3',
      rating: 4.5,
      numReviews: 6,
      countInStock: 20,
      isFeatured: true,
    },
    {
      name: 'free shirt 4',
      category: 'Shirts',
      slug: 'shirts-4',
      image: '/images/shirt4.jpeg',
      banner: '/images/shirt1.jpeg',
      price: 11,
      brand: 'nike',
      description: 'free shirt 4',
      rating: 4.5,
      numReviews: 6,
      countInStock: 20,
      isFeatured: true,
    },
    {
      name: 'free shirt 5',
      category: 'Shirts',
      slug: 'shirts-5',
      image: '/images/shirt5.jpeg',
      banner: '/images/shirt1.jpeg',
      price: 75,
      brand: 'nike',
      description: 'free shirt 5',
      rating: 4.5,
      numReviews: 6,
      countInStock: 20,
      isFeatured: true,
    },
    {
      name: 'free shirt 6',
      category: 'Shirts',
      slug: 'shirts-6',
      image: '/images/shirt6.jpeg',
      banner: '/images/shirt1.jpeg',
      price: 98,
      brand: 'nike',
      description: 'free shirt 6',
      rating: 4.5,
      numReviews: 6,
      countInStock: 20,
      isFeatured: true,
    },
  ],
}
export default data
